name: Release

on:
  push:
    tags:
      - nightly-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: |
          corepack enable
          yarn install --frozen-lockfile
      
      - name: Set env
        run: echo "RELEASE_FILE=qb-web-${GITHUB_REF#refs/*/}.zip" >> $GITHUB_ENV

      - name: Pack Release
        run: |
          yarn run build
          cd dist
          zip -r ../$RELEASE_FILE .

      - id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          prerelease: true
          files: ${{ env.RELEASE_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
